[package]
name = "core-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcore = { path = "../core-lib" }
oso-derive = { path = "../oso-derive" }